---
driver:
  name: docker
  privileged: true
  use_sudo: false

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  product_name: chef
  product_version: 14.13.11

verifier:
  name: inspec

platforms:
  - name: centos-7.3
    driver_config:
      run_command: /usr/sbin/init
      privileged: true
      provision_command:
        - systemctl enable sshd.service

suites:
  - name: lb
    driver:
      run_options: --network=mytestnet --ip=10.1.1.2
      forward: 80:80
    run_list:
      - recipe[company-haproxy::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: web1
    driver:
      run_options: --network=mytestnet --ip=10.1.1.3
    run_list:
      - recipe[lcd_web::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: web2
    driver:
      run_options: --network=mytestnet --ip=10.1.1.4
    run_list:
      - recipe[lcd_web::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:

